#services:
#  - type: web
#    name: flask-backend
#    plan: free
#    env: docker
#    dockerfilePath: ./Dockerfile  # Render builds from this file
#    envVars:
#      - key: DATABASE_URL
#        fromDatabase:
#          name: flask-db
#          property: connectionString
#databases:
#  - name: userdb
#    plan: free
