#services:
#  - type: web
#    name: flask-backend
#    plan: free
#    env: docker
#    dockerfilePath: ./Dockerfile  # Render builds from this file
#    envVars:
#      - key: DATABASE_URL
#        fromDatabase:
#          name: flask-db
#          property: connectionString
#databases:
#  - name: userdb
#    plan: free

postgresql://admin:7jTMjZ4LHkJ0j2toPxw2bYBHkI3CZwWR@dpg-curu1pi3esus73fgmns0-a.oregon-postgres.render.com/userdb_k6ui
